import { Component, OnInit } from '@angular/core';
import { Gender } from 'src/app/admin/providers/enum/gender.enum';

@Component({
  selector: 'app-customers-table',
  templateUrl: './customers-table.component.html',
  styleUrls: ['./customers-table.component.scss'],
})
export class CustomersTableComponent implements OnInit {
  ELEMENT_DATA = [
    {
      id: 1,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 2,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 3,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 4,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 5,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 6,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 7,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 8,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 9,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 10,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
    {
      id: 11,
      fullName: 'Le Quoc Hung',
      firstName: 'Le',
      lastName: 'Quoc Hung',
      dob: '12/03/1997',
      age: 23,
      email: 'lequochung19971@gmail.com',
      phone: '0329442883',
      gender: Gender.M,
    },
  ];
  dataSource = this.ELEMENT_DATA;
  displayedColumns: string[] = ['fullName', 'dob', 'age', 'gender', 'phone', 'email', 'action'];
  constructor() {}

  ngOnInit(): void {}
}
